November address attributions
OvertureMaps/docs pull request #129
Opened 2024-11-11 21:46 UTC by jeffdefacto

## Pull Request

### Docs Preview:

[Docs preview for this PR.](https://dfhx9f55j8eg5.cloudfront.net/how-to/pr/<PUT THE PR # HERE>)

View all staged runs:
https://github.com/OvertureMaps/docs/actions/workflows/publish-pr-to-staging.yml

2024-11-11 22:05 UTC, stepps00 approved these changes
A couple nits about links and formatting, otherwise looking great

2024-11-11 22:05 UTC, stepps00 commented on docs/attribution.mdx
> +- © Väestörekisterikeskus. Available under CC BY 4.0. Distributed by OpenAddresses. Accessed: 2024-11-10.
Looking at the OA source, we might be able to link to https://www.avoindata.fi/data/fi/dataset/rakennusten-osoitetiedot-koko-suomi here

2024-11-11 22:05 UTC, stepps00 commented on docs/attribution.mdx
> +- Data from [The national address site of the French Republic](https://adresse.data.gouv.fr/). Available under [LICENCE OUVERTE / OPEN LICENCE V2 - Etalab 2.0](https://etalab.gouv.fr/). Distributed b
License page is now located at: https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf

2024-11-11 22:05 UTC, stepps00 commented on docs/attribution.mdx
> +- City of Rostock data from [Hanse- und Universitätsstadt Rostock │](http://www.opendata-hro.de/). Available under [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/). Distributed by OpenAd
Extra ` |` in the source name?

2024-11-11 22:05 UTC, stepps00 commented on docs/attribution.mdx
> +- G-NAF © [Geoscape Australia](https://geoscape.com.au/) licensed by the Commonwealth of Australia. Available under the [Open Geo-coded National Address File End User Licence Agreement](https://geosc
Looks like this license page is now at: https://geoscape.com.au/wp-content/uploads/2024/08/EULA-G-NAF-Core-1.pdf

2024-11-13 12:06 UTC, danabauer requested changes
addresses is getting to be a beast! let's make the attribution list for each theme a collapsible section:
```
<details>
    <summary>
    **Addresses**
    </summary>
attribution list here
</details>
```

2024-11-13 15:41 UTC, jeffdefacto commented
Definitely cleaner now

2024-11-13 16:06 UTC, danabauer approved these changes

2024-11-13 21:02 UTC, merged